### PR TITLE
Support keras 3

### PR DESCRIPTION
**Pull request by nicolas-combaret**
Hello,

This is my first contribution on a public repository on GitHub.

This pull request aims at making classification_models_3D compatible with keras>=3. I made some changes that might not be welcomed, please let me know.

### CODE REVIEW

**Comment by ZFTurbo** [comment]
Thank you. Very great PR. Unfortunately there are 2 problems:

1) Other repository heavy dependent on this: https://github.com/ZFTurbo/segmentation_models_3D. So we need to first update it to keras3 too.
2) I can't check this code now myself. So we need to wait for some reviews and testing first.

**Comment by nicolas-combaret** [comment]
Hello,
 1. The main reason why I created this PR is because of this other repository :) I plan to create a PR on segmentation_models_3dD too, ASAP. 
 2. I don't know how to handle this second point. Please let me know.

**Comment by ZFTurbo** [comment]
If you make PR for 2nd repository too, I will find time to check all and Merge it into main branch. )

**Comment by ZFTurbo** [comment]
I'm testing. When I try to run `tst_keras_tensorflow.py` I have:

```
Keras version 3.3.3 using tensorflow backend
Traceback (most recent call last):
  File "tst_keras_tensorflow.py", line 76, in <module>
    tst_keras()
  File "tst_keras_tensorflow.py", line 69, in tst_keras
    model = modelPoint(input_shape=(128, 128, 128, 3), include_top=include_top, weights=use_weights)
  File "classification_models_3D\models_factory.py", line 103, in wrapper
    return func(*args, **new_kwargs)
  File "classification_models_3D\models\resnet.py", line 372, in ResNet18
    return ResNet(
  File "classification_models_3D\models\resnet.py", line 218, in ResNet
    backend, layers, models, keras_utils = get_submodules_from_kwargs(kwargs)
  File "classification_models_3D\__init__.py", line 5, in get_submodules_from_kwargs
    backend = kwargs.get('backend', keras.backend)
AttributeError: module 'classification_models_3D.keras' has no attribute 'backend'
```

**Comment by nicolas-combaret** [comment]
Hello,

Keras 3.3.0 was released last Monday, after I created my python environment. And the API changed compared to 3.2 :) I will update my PR!

**Comment by nicolas-combaret** [comment]
I updated my branch and tested it with the following environment: tensorflow==2.16.2, torch==2.3.0, jax==0.4.26, keras==3.3.3.

**Pull request merged**
